version: '2'

services:
    cli:
        image: app/docker-web:cli
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
        volumes:
            - ./:/var/www/html
            - ./docker/ssh/:/app/.ssh/