Core\Domain\Entity\User:
  type: entity
  table: user
  name: User
  id:
    id:
      type: string
      length: 40
      id: true
      generator:
        strategy: NONE
  fields:
    name:
      type: string
      nullable: false
      length: 250
      options:
        fixed: false
    username:
      type: string
      nullable: false
      length: 250
      options:
        fixed: false
    createdAt:
      type: datetime
      nullable: true
      options:
        fixed: false
      column: created_at