Core\Domain\Entity\Friend:
  type: entity
  table: friend
  name: Friend
  id:
    id:
      type: string
      length: 40
      id: true
      generator:
        strategy: NONE
  fields:
    friendId:
      type: string
      nullable: false
      length: 250
      options:
        fixed: false
      column: friend_id
    state:
      type: string
      nullable: false
      length: 250
      options:
        fixed: false
    createdAt:
      type: datetime
      nullable: true
      options:
        fixed: false
      column: created_at
  manyToOne:
    user:
      targetEntity: Core\Domain\Entity\User
      inversedBy: Friend
      joinColumns:
        name: user
        referencedColumnName: id
