Core\Domain\Entity\Movie:
  type: entity
  table: movie
  name: Movie
  id:
    id:
      type: string
      length: 40
      id: true
      generator:
        strategy: NONE
  fields:
    name:
      type: string
      nullable: false
      length: 250
      options:
        fixed: false
    synopsis:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
    status:
      type: string
      nullable: false
      length: 250
      options:
        fixed: false
    createdAt:
      type: datetime
      nullable: true
      options:
        fixed: false
      column: created_at
  oneToMany:
    wishes:
      targetEntity: Core\Domain\Entity\Wish
      mappedBy: movie